blank_issues_enabled: false
contact_links:
  - name: ❓ Question or Other
    url: https://github.com/aldinokemal/go-whatsapp-web-multidevice/discussions/new/choose
    about: Ask a question or start a discussion.